version: '3'
services:
    mosquitto:
        build: .
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./mosquitto.conf:/etc/mosquitto/mosquitto.conf
            - ./file.pw:/etc/mosquitto/file.pw
            - ./passwd:/etc/mosquitto/passwd
